const images = {
  length0: require("./images/0.png"),
  length1: require("./images/1.png"),
  length2: require("./images/2.png"),
  length3: require("./images/3.png"),
  length4: require("./images/4.png"),
  length5: require("./images/5.png"),
  length6: require("./images/6.png"),
  length7: require("./images/7.png"),
  length8: require("./images/8.png"),
  length9: require("./images/9.png"),
  length10: require("./images/10.png"),
  length11: require("./images/11.png"),
  length12: require("./images/12.png"),
  length13: require("./images/13.png"),
  length14: require("./images/14.png"),
  length15: require("./images/15.png"),
  length16: require("./images/16.png"),
  length17: require("./images/17.png"),
  length18: require("./images/18.png"),
  length19: require("./images/19.png"),
  length20: require("./images/20.png"),
  length21: require("./images/21.png"),
  noFocus: require("./images/noFocus.png"),
  password: require("./images/password.png"),
  text: require("./images/text.png"),
};

export default images;
